### ISSUE TITLE
Can’t Update Feeds since 2.14

### ISSUE THREAD

**Issue by iBook140** [SSilence/selfoss#691]
Hello,

updated from 2.13 to 2.14 (not my first update). After the update I’m no longer able to update my feeds. When I hit the «Quellen aktualisieren» button on the bottom left, I get the following error message:
Can not refresh sources: Internal Server Error

In log the error is:
Error curl_setopt() [<a href='function.curl-setopt'>function.curl-setopt</a>]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set

EDIT: safe_mode is disabled!

Went back to 2.13 and everything works fine again.

Any suggestions what’s wrong here?

Kind regards
René

PS Same error in version 2.15-SNAPSHOT

**Comment by bbeardsley** [comment]
Probably same as #689 ?

**Comment by guzzisti** [comment]
Same issue here.

@bbeardsley
When using the update button in the ui, a renamed file should not matter?!

**Comment by martinsauter** [comment]
Shooting a bit in the dark here but try this one:

```
<Directory /var/www/selfoss214-snapshot-old>
    Options -Multiviews
    AllowOverride All
    Order allow,deny
    allow from all
</Directory>
```

in ```/etc/apache2/sites-available/default-ssl.conf``` (or http config file, depending on what you use). The Options -Multiviews is the important thing.

**Comment by martinsauter** [comment]
Some thoughts:

- Can you check (e.g. with Wireshark) if the update process fails immediately or if it starts with some sources and then runs into this issue for a particular source? (And if so, for which type of feed?)

-Does the update process work when you use an empty database (no entries, no feeds, i.e. totally clean, i.e. rename selfoss.db for a while so a new one is created) and just add one or two simple RSS feeds (i.e. nothing special)?

-Can you set debug to 1 in common.php in Selfoss' root directory and then check data/logs/default.logs?

**Comment by niol** [comment]
Can you try this and let me know?

```diff
diff --git a/libs/f3/web.php b/libs/f3/web.php
index dfaf12e..d46ef06 100644
--- a/libs/f3/web.php
+++ b/libs/f3/web.php
@@ -249,6 +249,8 @@ class Web extends Prefab {
        **/
        protected function _curl($url,$options) {
                $curl=curl_init($url);
+               curl_setopt($curl,CURLOPT_REDIR_PROTOCOLS, CURLPROTO_HTTP |
+                                                   CURLPROTO_HTTPS);
                curl_setopt($curl,CURLOPT_FOLLOWLOCATION,
                        $options['follow_location']);
                curl_setopt($curl,CURLOPT_MAXREDIRS,
```

**Comment by iBook140** [comment]
Hello,

first of all please excuse the delay!

@bbeardsley 
I tried to duplicate cliupdate.php and rename it in update.php. Same error message

@martinsauter 
I set debug to 1 in common.php in Selfoss‘ root directory. Here what’s in the logs:
08-06-15 14:44:58 Error curl_setopt() [<a href='function.curl-setopt'>function.curl-setopt</a>]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set
/www/htdocs/w*****/rss_dev/libs/f3/web.php:253
/www/htdocs/w*****/rss_dev/libs/f3/web.php:508
/www/htdocs/w*****/rss_dev/helpers/WebClient.php:42
/www/htdocs/w*****/rss_dev/helpers/Image.php:43
/www/htdocs/w*****/rss_dev/spouts/rss/feed.php:256
/www/htdocs/w*****/rss_dev/helpers/ContentLoader.php:160
/www/htdocs/w*****/rss_dev/helpers/ContentLoader.php:46
/www/htdocs/w*****/rss_dev/controllers/Index.php:192
/www/htdocs/w*****/rss_dev/index.php:97

@niol 
Can you please explain me, where to paste this code?

Thanks @all :-)

**Comment by niol** [comment]
My message asks you to add the green lines in libs/f3/web.php after the curl_init line and try again.

**Comment by iBook140** [comment]
Hello,

I added the green lines in web.php (set debug to 1) and keep getting the following errors:
08-07-15 6:58:30 Error curl_setopt() [<a href='function.curl-setopt'>function.curl-setopt</a>]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set
/www/htdocs/w*****/rss_dev/libs/f3/web.php:257
/www/htdocs/w*****/rss_dev/libs/f3/web.php:512
/www/htdocs/w*****/rss_dev/helpers/WebClient.php:42
/www/htdocs/w*****/rss_dev/helpers/Image.php:43
/www/htdocs/w*****/rss_dev/spouts/rss/feed.php:256
/www/htdocs/w*****/rss_dev/helpers/ContentLoader.php:160
/www/htdocs/w*****/rss_dev/helpers/ContentLoader.php:46
/www/htdocs/w*****/rss_dev/controllers/Index.php:192
/www/htdocs/w*****/rss_dev/index.php:97

:-(

**Comment by niol** [comment]
The following should fix it.

```diff
--- a/libs/f3/web.php
+++ b/libs/f3/web.php
@@ -399,7 +399,7 @@ class Web extends Prefab {
        function engine($arg='curl') {
                $arg=strtolower($arg);
                $flags=array(
-                       'curl'=>extension_loaded('curl'),
+                       'curl'=>extension_loaded('curl') && ini_get('open_basedir') == '',
                        'stream'=>ini_get('allow_url_fopen'),
                        'socket'=>function_exists('fsockopen')
                );
```

Note that if you have access to your server configuration, you can disable the ```open_basedir``` option.

Please follow up.

**Comment by iBook140** [comment]
Hello,

still no luck:
08-07-15 15:06:59 Error mkdir() [<a href='function.mkdir'>function.mkdir</a>]: Keine Berechtigung
/www/htdocs/w0+++++/rss_dev/libs/f3/web.php:831
/www/htdocs/w0+++++/rss_dev/libs/f3/web.php:313
/www/htdocs/w0+++++/rss_dev/libs/f3/web.php:512
/www/htdocs/w0+++++/rss_dev/helpers/WebClient.php:42
/www/htdocs/w0+++++/rss_dev/helpers/Image.php:43
/www/htdocs/w0+++++/rss_dev/spouts/rss/feed.php:256
/www/htdocs/w0+++++/rss_dev/helpers/ContentLoader.php:160
/www/htdocs/w0+++++/rss_dev/helpers/ContentLoader.php:46
/www/htdocs/w0+++++/rss_dev/controllers/Index.php:192
/www/htdocs/w0+++++/rss_dev/index.php:97

Keine Berechtigung means something like no access. 

My hosted is all-inkling.com, I'm not sure, but I think that open_basedir is disabled there by default. 

Kind regards
Renè

**Comment by niol** [comment]
OK your setup is quite constrained.

What if you create a ```tmp/``` directory writeable by the webapp?

**Comment by iBook140** [comment]
Hello,

I think I’ll stay at version 2.13 which works fine with my setup. My web host told me, that open_basedir is enabled and can be changed when running PHP in CGI mode. But this leads me to other problems an restrictions.

Maybe there will be a version, that doesn’t have problems with open_basedir enabled once.

**Comment by niol** [comment]
If you do not help me fix this regarding a setup I do not have access to, this won't be fixed and you'll have to stick with 2.13. The change I proposed fixes the curl issue. But leads to other problems. When you have time for this, maybe we could follow up.

**Comment by iBook140** [comment]
Okay, thank you very much for your help, let’s continue :)

I edited the post above, when I change permissions to 777 for the folder where selfoss is installed it seems to work. Please tell me what I should do next?

**Comment by willem2668** [comment]
@niol
Your line of code solved the problem with my hosting provider
```php
'curl'=>extension_loaded('curl') && ini_get('open_basedir') == '',
```
THX

For your info:
* due to access rights I can't disable the open_basedir option
* before changing web.php, the apache error looks like:
```
AH01071: Got error 'PHP message: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set\n'
```

**Comment by mkyral** [comment]
Hi. I can confirm, that this workaround works. Thanks a lot.

**Comment by jtojnar** [comment]
Fixed in #700.
